apiVersion: v1
kind: Namespace
metadata:
  name: sso-gateway
  labels:
    app.kubernetes.io/part-of: sso-migration
    purpose: identity-routing
  annotations:
    openshift.io/description: "IdP Gateway Proxy for parallel RH-SSO / RHBK token exchange"
