apiVersion: v1
kind: Service
metadata:
  name: token-proxy-legacy
  namespace: sso-gateway
  labels:
    app: token-proxy-legacy
    app.kubernetes.io/part-of: sso-migration
    app.kubernetes.io/component: token-exchange-proxy
spec:
  selector:
    app: token-proxy-legacy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: token-proxy-migrated
  namespace: sso-gateway
  labels:
    app: token-proxy-migrated
    app.kubernetes.io/part-of: sso-migration
    app.kubernetes.io/component: token-exchange-proxy
spec:
  selector:
    app: token-proxy-migrated
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
